"use client";

// =======================================================================

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// =======================================================================

import Navbar from "./modules/navbar/navbar_1/navbar.jsx";
import Footer from "./modules/footer/footer_1/footer.jsx";
import { usePathname } from "next/navigation";

// =======================================================================

import { AppProvider } from "@/app/context/AppContext.jsx";

// =======================================================================

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // =======================================================================

  const pathname = usePathname();

  // Define the pages where you want to hide the NavBar
  const hideNavBarPages = ["/login"];

  const shouldShowNavBar = !hideNavBarPages.includes(pathname);

  // =======================================================================

  return (
    <>
      <html lang="en">
        {/* ------------------------------------- */}
        <head>
          <link rel="icon" href="/favicon.ico" />
          <title>My Project</title>
        </head>
        {/* ------------------------------------- */}
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          {/* _________________________________________________________________________________ */}
          <AppProvider>

            {/* ================================================= */}
            {shouldShowNavBar && <Navbar />}
            {/* ================================================= */}
            {children}
            {/* ================================================= */}
            {shouldShowNavBar && <Footer />}
            {/* ================================================= */}

          </AppProvider>
          {/* _________________________________________________________________________________ */}
        </body>
      </html>
    </>
  );
}
